/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.awt.event.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.*;

public class Apartments_Table extends javax.swing.JPanel {
    MySqlConnect c;
    
    
   
    public Apartments_Table() {
        initComponents();
        
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
        
        c = new MySqlConnect();
         ResultSet r = c.query("SELECT id, unit_name, description, unit_type, monthly_rate FROM apartment_units");
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
         while(r.next()) {
             String i = r.getString("id");
             String un = r.getString("unit_name");
             String d = r.getString("description");
             String ut = r.getString("unit_type");
             String mr = r.getString("monthly_rate");
             model.insertRow(jTable1.getRowCount(), new Object[] {i, un, d, ut, mr, "Edit", "Delete"});



         }
        }catch(SQLException ex) {
            System.out.println(ex);
        }
        
        // add mouselistener for table
        jTable1.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
            // double-clicked
          if (e.getClickCount() == 2) {
               JTable target = (JTable)e.getSource();
               int column = target.getSelectedColumn();
               int row = target.getSelectedRow();
               
               // 5th column is delet
               int idval = Integer.parseInt(target.getModel().getValueAt(row, 0).toString());
               
               if (column == 4){
                   editApartment(idval);
                   
               }
               else if (column == 5){
                   deleteApartment(idval);
               }
          }
        }
      });
    }
    
    
    // Method to Edit Existing Apartment
    public void editApartment(int id){
        System.out.println("Edit: "+ id);
    }
    
    // Method to Delete Existing Apartment
    public void deleteApartment(int id){
        System.out.println("Delete: "+ id);
        
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(957, 530));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Room No.", "Description", "Status", "Rate/mo.", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 530));
        jTable1.setPreferredSize(new java.awt.Dimension(957, 530));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
