/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.awt.event.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Tennants_Table extends javax.swing.JPanel {

     MySqlConnect c;
  
    public Tennants_Table() {
        initComponents();
        
         jTable2.removeColumn(jTable2.getColumnModel().getColumn(0));
         jTable2.removeColumn(jTable2.getColumnModel().getColumn(5));
        
         c = new MySqlConnect();
         ResultSet r = c.query("SELECT id, firstname, lastname, birthdate, contact_no, status, apartment_id FROM tenants");
         DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        try {
         while(r.next()) {
             String i = r.getString("id");
             String fn = r.getString("firstname");
             String ln = r.getString("lastname");
             String bd = r.getString("birthdate");
             String cn = r.getString("contact_no");
             String s= r.getString("status");
             String ai = r.getString("apartment_id");
             model.insertRow(jTable2.getRowCount(), new Object[] {i, fn, ln, bd, cn, s, ai, "Edit", "Delete"});
         }
        }catch(SQLException ex) {
            System.out.println(ex);
        }
        
        // add table event listener
        jTable2.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
            // double-clicked
          if (e.getClickCount() == 2) {
               JTable target = (JTable)e.getSource();
               int column = target.getSelectedColumn();
               int row = target.getSelectedRow();
               
               // 5th column is delet
               int idval = Integer.parseInt(target.getModel().getValueAt(row, 0).toString());
               
               if (column == 5){
                   editTenant(idval);
               }
               else if (column==6){
                   deleteTenant(idval);
               }
          }
        }
      });
    }
    
    //edit Tenant obj to the database
    public void editTenant(int id){
        System.out.println("Edit Tenant # "+id);
    }
    
    // delete Tenant obj to the database
    public void deleteTenant(int id){
        System.out.println("Delete Tenant # "+id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(957, 530));
        setPreferredSize(new java.awt.Dimension(957, 530));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "First Name", "Last Name", "Birthdate", "Contact no.", "Status", "apartment_id", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setPreferredSize(new java.awt.Dimension(957, 530));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setResizable(false);
            jTable2.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
